image:
  repository: hasanalperen/bcfm
  tag: latest
  pullPolicy: Always

name: my_app

replicaCount: 1

service:
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
  hosts:
    - host:
      paths:
        - /