apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: my-ingress
  namespace: jenkins
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    ingress.kubernetes.io/rewrite-target: "/"
spec:
  rules:
  - host: bcfm.34.102.60.81.nip.io
    http:
      paths:
      - path: "/(bcfm|metrics)"
        pathType: Exact
        backend:
          serviceName: my-web-app-web
          servicePort: 80
