apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress
  namespace: jenkins
  annotations:
    kubernetes.io/ingress.class: nginx
  spec:
    rules:
    - host: bcfm.34.102.60.81.nip.io
      http:
        paths:
        - backend:
            service:
              name: my-web-app-web
              port:
                number: 80
          path: /bcfm
          pathType: Exact
        - backend:
            service:
              name: my-web-app-web
              port:
                number: 80
          path: /metrics
          pathType: Exact
